#! /bin/bash

pgrep -x sxhkd > /dev/null || sxhkd &
pgrep -x compton > /dev/null || compton &
pgrep -x dunst > /dev/null || dunst &
# pgrep -x clipit > /dev/null || clipit &
pgrep -x diodon > /dev/null || diodon &
pgrep -x nm-applet > /dev/null || nm-applet &
pgrep -x ssh-agent > /dev/null || ssh-agent -s -a ~/.cache/sshagent.socket

autorandr -c
# pacmd set-default-sink 1
xinput --set-prop $(xinput | perl -ne 'if(/TrackPoint.*id=(\d+)/) { print $1; }') 'libinput Accel Speed' -0.2

monitorcount=$(bspc query -M | wc -l)

if [ $monitorcount == "1" ]; then
  bspc monitor -d 1 2 3 4 5 6 7 8 9 10
  notify-send singlemonitor
  killall polybar
  polybar --reload bar &
elif [ $monitorcount == "3" ]; then
  bspc monitor primary -d 1 2 3 4 10
  bspc monitor ^2 -d 5 6 7 8
  bspc monitor ^3 -d 9
  notify-send triplemonitor
  killall polybar
  polybar --reload bar &
  xset s 1800
  xset dpms 1800 1800 1800
else
  bspc monitor primary -d 1 2 3 4 5 10
  bspc monitor ^2 -d 6 7 8 9
  notify-send dualmonitor
  killall polybar
   polybar --reload bar &
  # polybar --reload clock &
  xset s 1800
  xset dpms 1800 1800 1800
fi

hsetroot -tile ~/Pictures/wp.png -tint "#656565"
xsetroot -cursor_name left_ptr

bspc config remove_unplugged_monitors true
bspc config remove_disabled_monitors true

bspc config border_width         2
bspc config window_gap           0
# bspc config top_padding          12
# bspc config bottom_padding          2

bspc config focus_follows_pointer true
bspc config remove_disabled_monitors true

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='8' state=floating follow=on
bspc rule -a Thunar state=floating
